services:
    wordpress:
        image: wordpress:php8.3-apache
        ports:
            - "${WP_PORT:-5100}:80"
        environment:
            WORDPRESS_DB_HOST: mysql
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DEBUG: ${WORDPRESS_DEBUG:-0}
            PONPONCAT_VITE_HOST: "${VITE_HOST:-http://vite}:${VITE_PORT:-5103}"
            PONPONCAT_VITE_HOST_WEB: "${VITE_HOST_WEB:-http://localhost}:${VITE_PORT:-5103}"
        volumes:
            - ./test_theme:/var/www/html/wp-content/themes/test_theme
            - ./html:/var/www/html/
            - ./vendor:/var/www/html/wp-content/themes/test_theme/vendor
            - ./src:/var/www/html/wp-content/themes/test_theme/src
        depends_on:
            - mysql
        networks:
            - wordpress

    mysql:
        image: mysql:8.0
        ports:
            - "${DB_PORT:-5101}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
        volumes:
            - ./db:/var/lib/mysql
        networks:
            - wordpress
    phpmyadmin:
        image: 'phpmyadmin/phpmyadmin'
        links:
            - mysql:mysql
        ports:
            - "${PMA_PORT:-5102}:80"
        environment:
            PMA_USER: wordpress
            PMA_PASSWORD: wordpress
            PMA_HOST: 'mysql'
        networks:
            - wordpress

    vite:
        image: node:22
        container_name: vite
        working_dir: /app
        volumes:
            - ./:/app
            - /node_modules
        command: sh -c "npm run dev"
        ports:
            - "${VITE_PORT:-5103}:${VITE_PORT:-5103}"
        environment:
            VITE_HOST: '0.0.0.0'
            VITE_PORT: "${VITE_PORT:-5103}"
        networks:
            - wordpress

networks:
    wordpress:
        driver: bridge

volumes:
    db_data:
